name: iOS Tests

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: Build and Test
    runs-on: macos-14  # Use macOS 14 for Xcode 16 support
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      - name: Install xcbeautify
        run: brew install xcbeautify
      
      - name: Download iOS 18.2 Runtime
        run: |
          # Download and install iOS 18.2 runtime
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcrun simctl list runtimes
          xcrun simctl runtime add iOS18.2
          xcrun simctl list runtimes
      
      - name: Create iOS 18.2 Simulator
        run: |
          DEVICE_ID=$(xcrun simctl create "iPhone 15" "iPhone 15" iOS18.2)
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
          xcrun simctl boot "$DEVICE_ID"
      
      - name: Build and test
        run: |
          xcodebuild test \
            -project TypeBeat.xcodeproj \
            -scheme TypeBeat \
            -destination "platform=iOS Simulator,id=$DEVICE_ID" \
            -testPlan TypeBeatUITests \
            | xcbeautify
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          retention-days: 7 