name: iOS Tests

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: Build and Test
    runs-on: macos-14  # Use macOS 14 for Xcode 16 support
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      - name: Install xcbeautify
        run: brew install xcbeautify
      
      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -project TypeBeat.xcodeproj \
            -scheme TypeBeat \
            -destination 'platform=macOS,arch=arm64' \
            | xcbeautify
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Build/Products
          retention-days: 1 