name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-check:
    name: Code Check
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
    - name: Check Environment
      run: |
        sw_vers
        xcrun --sdk macosx --show-sdk-version
        xcodebuild -version
        
    - name: Compile Swift Files
      run: |
        # Find all Swift files in the project
        SWIFT_FILES=$(find . -name "*.swift" | grep -v "Tests")
        
        # Compile them without building a full app
        if [ -n "$SWIFT_FILES" ]; then
          xcrun swiftc -sdk $(xcrun --show-sdk-path --sdk macosx) -target x86_64-apple-macos14.7 -typecheck $SWIFT_FILES
          echo "Swift compilation check completed successfully"
        else
          echo "No Swift files found to check"
        fi 