name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  app-tests:
    name: App Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
    - name: Check Environment
      run: |
        sw_vers
        xcrun --sdk macosx --show-sdk-version
        xcodebuild -version
        
    - name: Explore Project Structure
      run: |
        echo "Project root contents:"
        ls -la
        
        echo "Tests directory contents:"
        ls -la Tests/ || echo "No Tests directory at root level"
        
        echo "TypeBeat directory contents:"
        ls -la TypeBeat/ || echo "No TypeBeat directory"
        
        echo "TypeBeat/Tests directory contents:"
        ls -la TypeBeat/Tests/ || echo "No TypeBeat/Tests directory"
        
        echo "Finding all Swift test files:"
        find . -name "*Test*.swift" -o -name "*test*.swift" || echo "No test files found"
        
        echo "Xcode project structure:"
        find TypeBeat.xcodeproj -type f -name "*.pbxproj" -exec cat {} \; | grep -A 5 "PBXNativeTarget.*Test" || echo "No test targets found in Xcode project"
        
    - name: Examine Test Files
      run: |
        # Find test files
        TEST_FILES=$(find . -name "*Test*.swift" -o -name "*test*.swift" | head -n 5)
        
        if [ -n "$TEST_FILES" ]; then
          echo "Found test files:"
          echo "$TEST_FILES"
          
          # Show the content of the first few test files
          for file in $TEST_FILES; do
            echo "=== Contents of $file ==="
            head -n 20 "$file"
            echo "=== End of preview ==="
          done
        else
          echo "No test files found in the project."
        fi
        
    - name: List Xcode Test Schemes
      run: |
        xcodebuild -list -project TypeBeat.xcodeproj || echo "Failed to list schemes"
        
    - name: Try Running Xcode Tests
      run: |
        # Try to run tests using xcodebuild
        xcodebuild test -project TypeBeat.xcodeproj -scheme "TypeBeatTests" -destination "platform=macOS" || echo "Failed to run tests with scheme TypeBeatTests" 