name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  app-tests:
    name: App Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
    - name: Check Environment
      run: |
        sw_vers
        xcrun --sdk macosx --show-sdk-version
        xcodebuild -version
        
    - name: List Xcode Test Schemes
      run: |
        xcodebuild -list -project TypeBeat.xcodeproj || echo "Failed to list schemes"
        
    - name: Run Tests with Mac Catalyst
      run: |
        # Run tests using Mac Catalyst destination
        xcodebuild test -project TypeBeat.xcodeproj -scheme "TypeBeatTests" -destination "platform=macOS,variant=Mac Catalyst" MACOSX_DEPLOYMENT_TARGET=14.7 || echo "Failed to run tests with Mac Catalyst" 