name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-check:
    name: Code Check
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
    - name: Check Environment
      run: |
        sw_vers
        xcrun --sdk macosx --show-sdk-version
        xcodebuild -version
        
    - name: Compile Swift Files
      run: |
        # Find Swift files only in the main project directories
        SWIFT_FILES=$(find ./TypeBeat -name "*.swift" | grep -v "Tests")
        
        # Add any other Swift files from the root directory
        ROOT_SWIFT_FILES=$(find . -maxdepth 1 -name "*.swift")
        if [ -n "$ROOT_SWIFT_FILES" ]; then
          SWIFT_FILES="$SWIFT_FILES $ROOT_SWIFT_FILES"
        fi
        
        # Compile them without building a full app
        if [ -n "$SWIFT_FILES" ]; then
          echo "Found Swift files to check:"
          echo "$SWIFT_FILES"
          
          # Use xcodebuild to check syntax only
          xcodebuild clean build -project TypeBeat.xcodeproj -scheme "TypeBeat" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -quiet -skipUnavailableActions -syntax-check
          
          echo "Swift compilation check completed successfully"
        else
          echo "No Swift files found to check"
        fi 