name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
        
    - name: Fix AppDelegate for macOS
      run: |
        cat > TypeBeat/AppDelegate.swift << 'EOF'
        import Foundation
        #if os(iOS)
        import UIKit
        
        class AppDelegate: NSObject, UIApplicationDelegate {
            func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
                return true
            }
        }
        #elseif os(macOS)
        import AppKit
        
        class AppDelegate: NSObject {
            // macOS implementation
        }
        #endif
        EOF
        
    - name: Build for macOS
      run: |
        xcodebuild clean build \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeat \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_TREAT_WARNINGS_AS_ERRORS=NO
      
    - name: Run Unit Tests
      if: success()
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatTests \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run UI Tests
      if: success()
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatUITests \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO 