name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
        
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show project info
      run: |
        xcodebuild -list -project TypeBeat.xcodeproj
        cat TypeBeat.xcodeproj/project.pbxproj | grep -A 5 "SUPPORTED_PLATFORMS"
        
    - name: Build for available platform
      run: |
        xcodebuild clean build \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeat \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_TREAT_WARNINGS_AS_ERRORS=NO
      
    - name: Run Unit Tests
      if: success()
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatTests \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run UI Tests
      if: success()
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatUITests \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO 