name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14 # Uses the latest macOS runner with Xcode 15+
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: List available schemes
      run: xcodebuild -list -project TypeBeat.xcodeproj
      
    - name: Build TypeBeat
      run: |
        xcodebuild clean build \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeat \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatTests \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run UI Tests
      run: |
        xcodebuild test \
          -project TypeBeat.xcodeproj \
          -scheme TypeBeatUITests \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO 